export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_ITEMS_IN_CATEGORY = 'GET_ITEMS_IN_CATEGORY';
export const GET_ITEM_IN_CATEGORY = 'GET_ITEM_IN_CATEGORY';